-- Automated Seed: User accounts
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS137-1721'), 'jefri', 'PNS137-1721@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS145-1721'), 'setiyono', 'PNS145-1721@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS013-1722'), 'taufik', 'PNS013-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS060-1722'), 'agusta', 'PNS060-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS144-1722'), 'saipul', 'PNS144-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS146-1722'), 'suriyadi', 'PNS146-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS132-1722'), 'budi', 'PNS132-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS135-1722'), 'indra', 'PNS135-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS102-1722'), 'namli', 'PNS102-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE069-1722'), 'miqbal', 'CE069-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE081-1722'), 'mazhari', 'CE081-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE161-1722'), 'rocky', 'CE161-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE078-1722'), 'diki', 'CE078-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE158-1722'), 'nurdiansyah', 'CE158-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE075-1722'), 'angga', 'CE075-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE074-1722'), 'munawir', 'CE074-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE162-1722'), 'ryan', 'CE162-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE164-1722'), 'sufridanto', 'CE164-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE154-1722'), 'juhalidi', 'CE154-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE169-1722'), 'zeni', 'CE169-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS126-1722'), 'agung', 'PNS126-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS136-1722'), 'jansen', 'PNS136-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS130-1722'), 'asrul', 'PNS130-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS143-1722'), 'rayusman', 'PNS143-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS147-1722'), 'syaibir', 'PNS147-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS128-1722'), 'ansyori', 'PNS128-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS138-1722'), 'junaidi', 'PNS138-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS103-1722'), 'pelita', 'PNS103-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE149-1722'), 'daniel', 'CE149-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE079-1722'), 'sigit', 'CE079-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE071-1722'), 'ari', 'CE071-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE070-1722'), 'mahfutzhi', 'CE070-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE163-1722'), 'siktus', 'CE163-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE080-1722'), 'hari', 'CE080-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE168-1722'), 'try', 'CE168-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE157-1722'), 'mricky', 'CE157-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE152-1722'), 'igif', 'CE152-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE076-1722'), 'clement', 'CE076-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE151-1722'), 'guntur', 'CE151-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS142-1722'), 'muhammad', 'PNS142-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS125-1722'), 'abdul', 'PNS125-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS011-1724'), 'maizar', 'PNS011-1724@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS148-1722'), 'wahyu', 'PNS148-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS127-1722'), 'agus', 'PNS127-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS129-1722'), 'ansyory', 'PNS129-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS140-1722'), 'magus', 'PNS140-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE073-1722'), 'langgeng', 'CE073-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE147-1722'), 'ahmad', 'CE147-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE077-1722'), 'krismanto', 'CE077-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE150-1722'), 'febri', 'CE150-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE167-1722'), 'syahrul', 'CE167-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE166-1722'), 'suwartoyo', 'CE166-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE153-1722'), 'ilham', 'CE153-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE165-1722'), 'suhendra', 'CE165-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE160-1722'), 'reza', 'CE160-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE155-1722'), 'mediyanto', 'CE155-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE159-1722'), 'rahmat', 'CE159-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'CE148-1722'), 'ansori', 'CE148-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS005-1721'), 'zulkarnain', 'PNS005-1721@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS052-1722'), 'khairul', 'PNS052-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS053-1722'), 'esra', 'PNS053-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS015-1722'), 'heru', 'PNS015-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS014-1722'), 'ranuh', 'PNS014-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS134-1722'), 'imam', 'PNS134-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;
INSERT INTO users (personnel_id, username, email, password_hash) VALUES ((SELECT id FROM personnels WHERE nip_nik = 'PNS141-1722'), 'mali', 'PNS141-1722@arff.hangnadim.id', '$2b$12$f6gY9rjtJiyLxzby/uVAZOT1ZggsGktM42rQ1K3EpaeS14ACA./pe') ON CONFLICT (personnel_id) DO NOTHING;

-- Map roles dynamically based on personnel positions
INSERT INTO personnel_roles (personnel_id, role_id)
SELECT u.personnel_id, 
       CASE p.position_id
            WHEN 1 THEN 3 -- Airport Rescue & Fire Fighting Manager -> Manager
            WHEN 2 THEN 2 -- Vice President -> Vice President
            WHEN 3 THEN 4 -- RFF Performance Standard Team Leader -> RFF Performance Standard Team Leader
            WHEN 4 THEN 5 -- RFF OperationTeam Leader -> RFF OperationTeam Leader
            WHEN 5 THEN 6 -- RFF Maintenance Team Leader -> RFF Maintenance Team Leader
            WHEN 6 THEN 8 -- Rescue and Fire Fighting Squad Leader -> Squad Leader
            WHEN 7 THEN 9 -- Rescue Officer -> Officer
            WHEN 8 THEN 1 -- Admin -> Superuser
            ELSE 9
       END
FROM users u
JOIN personnels p ON u.personnel_id = p.id
ON CONFLICT DO NOTHING;
