-- Migration to seed Fire Extinguishers from DAFTAR_FIRE_HOSE_REEL_HANG_NADIM_CLEAN.csv
INSERT INTO fire_extinguishers (id, serial_number, location_description, agent_type, capacity_kg, status)
VALUES
(uuid_generate_v4(), 'APAR-001', 'DEPAN BAKSO LAPANGAN TEMBAK LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-002', 'IMIGRASI LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-003', 'SAMPING IMIGRASI LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-004', 'PINTU KEDATANGAN LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-005', 'KONVAYOR 3 LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-006', 'KONVAYOR 1 LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-007', 'SAMPING OLP LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-008', 'SAMPING TRANSIT LION GROUP LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-009', 'DEPAN CITILINK LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-010', 'DEPAN CHECK IN LION AIR LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-011', 'DEPAN OFFICE CITILINK LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-012', 'SAMPING KANTOR IMIGRASI LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-013', 'RUANG TUNGGU LANTAI 1 PINTU 9', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-014', 'MUSHOLA AR-RAHIM LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-015', 'DEPAN IMIGRASI LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-016', 'RUANG TUNGGU LANTAI 2 PINTU A3', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-017', 'BELAKANG OLEH-OLEH BATAM E-BROWNIES LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-018', 'DEPAN MUSHOLA LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-019', 'SAMPING GATE WAY SHOP', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-020', 'SOTO MALANG LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-021', 'WARUNG SANNUR LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-022', 'SAMPING ROT''O LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-023', 'BLUE SKY LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-024', 'BELAKANG BOMBO LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-025', 'STARBUKS LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-026', 'DEPAN OLEH-OLEH BATAM JELITA LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-027', 'FOOD ACRADE LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-028', 'KANTOR OFFICE DI DEPAN PELAYANAN LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-029', 'TOILET OFFICE DEKAT PINTU MASUK LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-030', 'OFFICE KARGO', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-031', 'GUDANG KARGO', 'FOAM', 9, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-032', 'GUDANG KARGO', 'FOAM', 9, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-033', 'DALAM TOILET DEKAT RUANG TUNGGU A6/A7', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-034', 'PANTRI DAN DEPAN PINTU MASUK LANTAI 2 OFFICE', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-035', 'DEPAN TOKO PISANG VILLA LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-036', 'TOILET KEDATANGAN  DEKAT TRANSIT', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-037', 'SEBELAH INDOMARET KEBERANGKATAN', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-038', 'ANJUNGAN SDM', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-039', 'ANJUNGAN KANTOR KONTRAKTOR AC', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-040', 'SEBELAH KANTOR BEA CUKAI LANTAI 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-U041', 'DEKAT X-RAY LANTAI 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-042', 'RUANG TUNGGU A2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-044', 'RUANG TUNGGU A5', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-045', 'RUANG TUNGGU A6', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-046', 'RUANG TUNGGU A7', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-047', 'RUANG TUNGGU A8', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-048', 'RUANG TUNGGU A9', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-049', 'MUSHOLA LANTAI 2 RUANG TUNGGU A8', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-050', 'DEPAN KANTOR POSKO', 'CO2', 5, 'MAINTENANCE'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-051', 'SEBELAH INDOMARET KEBERANGKTAN', 'CO2', 5, 'MAINTENANCE'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-052', 'DEPAN FORTUNE SHOP', 'CO2', 5, 'MAINTENANCE'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-053', 'KEBERANGKATAN DEKAT TROLLY', 'CO2', 5, 'MAINTENANCE'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-054', 'BELAKANG KANTOR BANK MANDIRI', 'CO2', 5, 'MAINTENANCE'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-055', 'FOOD PLAZA LANTAI 2', 'CO2', 5, 'MAINTENANCE'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-056', 'RUANG TUNGGU A1', 'CO2', 5, 'MAINTENANCE'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-057', 'DEPAN SCANDES PARFUM', 'CO2', 5, 'MAINTENANCE'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-058', 'RUANG TUNGGU A4', 'CO2', 5, 'MAINTENANCE'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-059', 'KANTOR BEA CUKAI LANTAI 2', 'CO2', 5, 'MAINTENANCE'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-059', 'RUANG TUNGGU A3', 'CO2', 5, 'MAINTENANCE'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-060', 'RUANG PANEL  KANTOR ATAS FF 1.1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-061', 'RUANG PANEL DI TANGGA ANJUNGAN KANTOR ATAS', 'Dry Chemical Powder', NULL, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-062', 'RUANG PANEL FF 2.2 ANJUNGAN DEKAT KANTOR BNN', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-063', 'RUANG PANEL GF 3', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-064', 'RUANG TRAFO SEBEAH RUANG MESIN POMPA', 'CO2', 9, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-065', 'RUANG PANEL GF 1', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-066', 'RUANG PANEL GF 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-067', 'RUANG PANEL CARGO SEBELAH KANTOR GARUDA', 'Dry Chemical Powder', NULL, 'OUT_OF_SERVICE'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-068', 'RUANG SUBSTATION 2', 'CO2', 5, 'READY'::fire_extinguisher_status_enum),
(uuid_generate_v4(), 'APAR-069', 'VOR 22', 'CO2', 5, 'READY'::fire_extinguisher_status_enum)
ON CONFLICT (serial_number) DO NOTHING;
